// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgiqwhsawkyugcipaxqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnaXF3aHNhd2t5dWdjaXBheHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Mzc1NTMsImV4cCI6MjA2MTAxMzU1M30.BQYv-J1nrPdOIuhlZB4HNvqXyP6-V11S5I8C0zfkRro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);